title: Vanlife Wiki
email: hello@world.com
description: >- # this means to ignore newlines until "baseurl:"
  Wiki for all fun things
baseurl: "/VanlifeWiki" # the subpath of your site, e.g. /blog
url: "https://kaydedubya.github.io/VanlifeWiki" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: redcarpet
theme: minima

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "highlight", "with_toc_data"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
